apiVersion: v1
kind: Pod
metadata:
  name: httpd
  labels:
    app: LaboConnect
#    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
#    release: "{{ .Release.Name }}"
#    heritage: "{{ .Release.Service }}"
spec:
  containers:
  - name: {{ template "fullname" . }}
    image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
    imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
    ports:
    - name: https
      containerPort: 443
    volumeMounts:
    - mountPath: /etc/localtime
      name: localtime
  imagePullSecrets:
  - name: regcred 
  volumes:
  - name: localtime
    hostPath:
      path: /etc/localtime
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: LaboConnect2
  name: postgres
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: LaboConnect2
    spec:
      containers:
      - name: postgres
        image: "{{ .Values.mariadb.image.repository }}:{{ .Values.mariadb.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        ports:
        - name: postgres
          containerPort: 5432
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
        - name: zoneinfo
          mountPath: /usr/share/zoneinfo
        #- name: postgresql
        #  mountPath: /var/lib/pgsql/data
      imagePullSecrets:
      - name: regcred
      volumes:
      - hostPath:
          path: "/etc/localtime"
        name: localtime
      - hostPath:
          path: "/usr/share/zoneinfo"
        name: zoneinfo
---
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  labels:
    app: LaboConnect3
  name: jboss
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: LaboConnect3
    spec:
      containers:
      - name: jboss
        #image: docker-01.progi.loc:5000/dev/laboconnect:LC03.06mbi
        image: "{{ .Values.jboss.repository }}:{{ .Values.jboss.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        ports:
        - name: postgres
          containerPort: 7070
      imagePullSecrets:
      - name: regcred

