apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  namespace: lc
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: NodePort
  ports:
    - name: https
      port: 443
      targetPort: 443
      {{- if (and (eq .Values.serviceType "NodePort") (not (empty .Values.nodePorts.https)))}}
      nodePort: {{ .Values.nodePorts.https }}
      {{- end }}
  selector:
#    app: {{ template "fullname" . }}
    app: LaboConnect 
---
apiVersion: v1
kind: Service
metadata:
  name: pg
  namespace: lc
  labels:
    app: Laboconnect2
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: NodePort
  ports:
    - name: postgres
      port: 5432
      nodePort: {{ .Values.nodePorts.postgres }}
      targetPort: 5432
#    selector:
#      app: LaboConnect2
